config/routes.rb
Dreams::Application.routes.draw do
  resources :servers

  resources :apps

  resources :environments

 
  resources :environments do
    member do
      get :servers
    end
  end
 
  resources :apps do
    member do
      get :servers
    end
  end

  root to: 'environments#index', as: 'environments_home'

end

app/models/server.rb
class Server < ActiveRecord::Base
  belongs_to :environment
  belongs_to :app
  default_scope :order => 'environment_id, app_id, name'
  attr_accessible :app_id, :app_last_updated, :app_version, :environment_id, :name, :os, :os_last_updated, :os_version
  validates :name, :app_id, :environment_id, presence: true
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servers }
    end
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
    @server = Server.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/new
  # GET /servers/new.json
  def new
    @server = Server.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @server }
    end
  end

  # GET /servers/1/edit
  def edit
    @server = Server.find(params[:id])
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(params[:server])

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render json: @server, status: :created, location: @server }
      else
        format.html { render action: "new" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servers/1
  # PUT /servers/1.json
  def update
    @server = Server.find(params[:id])

    respond_to do |format|
      if @server.update_attributes(params[:server])
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server = Server.find(params[:id])
    @server.destroy

    respond_to do |format|
      format.html { redirect_to servers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="select">
    <%= f.label :environment_id %><br />
    <%= f.collection_select(:environment_id, Environment.all, :id, :name) %>
  </div>
  <div class="select">
    <%= f.label :app_id %><br />
    <%= f.collection_select(:app_id, App.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :app_version %><br />
    <%= f.text_field :app_version %>
  </div>
  <div class="field">
    <%= f.label :app_last_updated %><br />
    <%= f.date_select :app_last_updated %>
  </div>
  <div class="field">
    <%= f.label :os %><br />
    <%= f.text_field :os %>
  </div>
  <div class="field">
    <%= f.label :os_version %><br />
    <%= f.text_field :os_version %>
  </div>
  <div class="field">
    <%= f.label :os_last_updated %><br />
    <%= f.date_select :os_last_updated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>Server Listing</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Environment</th>
    <th>App</th>
    <th>App last updated</th>
    <th>Operating System(OS)</th>
  </tr>

<% @servers.each do |server| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= link_to server.name, server %></td>
    <td><%= server.environment.name %></td>
    <td><%= server.app.name %></td>
    <td><%= server.app_last_updated %></td>
    <td><%= server.os + " " + server.os_version %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p>
  <b>Name:</b>
  <%= @server.name %>
</p>

<p>
  <b>Os:</b>
  <%= @server.os %>
</p>

<p>
  <b>Os version:</b>
  <%= @server.os_version %>
</p>

<p>
  <b>Os last updated:</b>
  <%= @server.os_last_updated %>
</p>

<p>
  <b>App version:</b>
  <%= @server.app_version %>
</p>

<p>
  <b>App last updated:</b>
  <%= @server.app_last_updated %>
</p>

<p>
  <b>Environment:</b>
  <%= @server.environment.name %>
</p>

<p>
  <b>App:</b>
  <%= @server.app.name %>
</p>


<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Delete', @server, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', :back %> |
<%= link_to 'New', new_server_path %>