config/routes.rb
Dreams::Application.routes.draw do
  resources :servers

  resources :apps

  resources :environments

 
  resources :environments do
    member do
      get :servers
    end
  end
 
  resources :apps do
    member do
      get :servers
    end
  end

  root to: 'environments#index', as: 'environments_home'

end

app/models/environment.rb
class Environment < ActiveRecord::Base
  has_many :servers
  attr_accessible :description, :integrated, :name
  validates :name, :description, presence: true
  validates :name, uniqueness: true
  before_destroy :ensure_not_referenced_by_any_server

  private
  def ensure_not_referenced_by_any_server
    if servers.empty?
      return true
    else
      errors.add(:base, "There are still servers that belong to the #{self.name} environment!")
      return false
    end
  end
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  # GET /environments
  # GET /environments.json
  def index
    @environments = Environment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @environments }
    end
  end

  # GET /environments/1
  # GET /environments/1.json
  def show
    @environment = Environment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @environment }
    end
  end

  # GET /environments/1/servers
  # GET /environments/1.json
  def servers
    @servers = Server.where(["servers.environment_id = ?", params[:id]])
    if @servers.empty?
      @servers = Server.all
      flash[:notice] = 'No servers assigned to this environment yet, showing all servers.'
      render 'servers/index' and return
    end
    render 'servers/index'
  end

  # GET /environments/new
  # GET /environments/new.json
  def new
    @environment = Environment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @environment }
    end
  end

  # GET /environments/1/edit
  def edit
    @environment = Environment.find(params[:id])
  end

  # POST /environments
  # POST /environments.json
  def create
    @environment = Environment.new(params[:environment])

    respond_to do |format|
      if @environment.save
        format.html { redirect_to @environment, notice: 'Environment was successfully created.' }
        format.json { render json: @environment, status: :created, location: @environment }
      else
        format.html { render action: "new" }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /environments/1
  # PUT /environments/1.json
  def update
    @environment = Environment.find(params[:id])

    respond_to do |format|
      if @environment.update_attributes(params[:environment])
        format.html { redirect_to @environment, notice: 'Environment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /environments/1
  # DELETE /environments/1.json
  def destroy
    @environment = Environment.find(params[:id])
    if @environment.destroy
      flash[:notice] = "#{@environment.name} environment has been deleted."
    else
      flash[:alert] = "A Validation Error Occurred! #{@environment.errors[:base].to_s}"
    end

    respond_to do |format|
      format.html { redirect_to environments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/views/environments/_form.html.erb
<%= form_for(@environment) do |f| %>
  <% if @environment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@environment.errors.count, "error") %> prohibited this environment from being saved:</h2>

      <ul>
      <% @environment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :integrated %><br />
    <%= f.check_box :integrated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/environments/edit.html.erb
<h1>Editing environment</h1>

<%= render 'form' %>

<%= link_to 'Show', @environment %> |
<%= link_to 'Back', environments_path %>

app/views/environments/index.html.erb
<h1>Environments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Integrated</th>
    <th class="list_actions"></th>
  </tr>

<% @environments.each do |environment| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= link_to environment.name, servers_environment_path(environment.id) %></td>
    <td><%= environment.description %></td>
    <td><%= environment.integrated %></td>
    <td class="list_actions">
      <%= link_to 'Show', environment %><br/>
      <%= link_to 'Edit', edit_environment_path(environment) %><br/>
      <%= link_to 'Delete', environment, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Environment', new_environment_path %>

app/views/environments/new.html.erb
<h1>New environment</h1>

<%= render 'form' %>

<%= link_to 'Back', environments_path %>

app/views/environments/servers.html.erb
<p>
  <b>Name:</b>
  <%= @environment.name %>
</p>

<p>
  <b>Description:</b>
  <%= @environment.description %>
</p>

<p>
  <b>Integrated:</b>
  <%= @environment.integrated %>
</p>

<%= link_to 'Edit', edit_environment_path(@environment) %> |
<%= link_to 'Back', environments_path %> |
<%= link_to 'New', new_environment_path %>

app/views/environments/show.html.erb
<p>
  <b>Name:</b>
  <%= @environment.name %>
</p>

<p>
  <b>Description:</b>
  <%= @environment.description %>
</p>

<p>
  <b>Integrated:</b>
  <%= @environment.integrated %>
</p>


<%= link_to 'Edit', edit_environment_path(@environment) %> |
<%= link_to 'Back', environments_path %> |
<%= link_to 'New', new_environment_path %>