config/routes.rb
Dreams::Application.routes.draw do
  resources :servers

  resources :apps

  resources :environments

 
  resources :environments do
    member do
      get :servers
    end
  end
 
  resources :apps do
    member do
      get :servers
    end
  end

  root to: 'environments#index', as: 'environments_home'

end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dev_lead %><br />
    <%= f.text_field :dev_lead %>
  </div>
  <div class="field">
    <%= f.label :support_lead %><br />
    <%= f.text_field :support_lead %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Applications</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Dev lead</th>
    <th>Support lead</th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= link_to app.name, servers_app_path(app.id) %></td>
    <td><%= app.dev_lead %></td>
    <td><%= app.support_lead %></td>
    <td class="list_actions">
      <%= link_to 'Show', app %><br/>
      <%= link_to 'Edit', edit_app_path(app) %><br/>
      <%= link_to 'Delete', app, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p>
  <b>Name:</b>
  <%= @app.name %>
</p>

<p>
  <b>Dev lead:</b>
  <%= @app.dev_lead %>
</p>

<p>
  <b>Support lead:</b>
  <%= @app.support_lead %>
</p>


<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %> |
<%= link_to 'New', new_app_path %>